on:
  push:
    branches:
      - homolog
name: ğŸš€ Deploy Short Link Homolog
defaults:
  run:
    working-directory: ./
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ”« Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: â› Build Project
        run: |
          yarn
          yarn build --mode homolog

      - name: âœ” List output files
        run: ls

      - name: ğŸŒ Sync files to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: short.mag3s.com
          username: homolog@short.mag3s.com
          password: ${{ secrets.PASSFTP }}
          local-dir: ./dist/
          server-dir: /
          exclude: |
            **/.well-known/**
            **/cgi-bin/**
            .htaccess
            .ftpquota
            robots.txt
          dry-run: false

      - name: ğŸ“¤ Send Message Telegram Deploy
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Commit criado por: ${{ github.actor }}!
            O que foi feito: ${{ github.event.commits[0].message }}

            Ambiente: Short Link HomologaÃ§Ã£o

            Veja mais detalhes em: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          disable_web_page_preview: true
